# Generated by Django 5.1.1 on 2026-04-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='created_by',
            new_name='created_at',
        ),
    ]
