# Generated by Django 5.2.15 on 2026-08-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheels', '0004_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
    ]
